name: Basic CI Pipeline

on: [pull_request]

# on:
#   push:
#     branches: [ main ]

env:
  AWS_REGION: us-east-1
  BUCKET_NAME: fer1035-github-labs
  TEST_PATH: ./test_files/aws-network/
  LOG_PATH: ./logs.txt
  LIST_PATH: ./list.txt
  POSTLIST_PATH: ./postlist.txt

jobs:
  pr:
    runs-on: ubuntu-latest

    steps:

      - name: Check out repository code
        uses: actions/checkout@v7
        # with:
        #   fetch-depth: 0

      # - name: Restore Git timestamps
      #   uses: chetan/git-restore-mtime-action@v2

      # - name: Log message
      #   run: echo "Hello World! The workflow is running successfully."

      # - name: Run a basic command
      #   run: node --version

      # - name: Install AWS CLI
      #   run: |
      #     curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      #     unzip awscliv2.zip
      #     sudo ./aws/install
      #     aws --version

      - name: Check AWS CLI version
        run: aws --version

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Print AWS STS identity
        run: aws sts get-caller-identity

      - name: Get PWD amd list files
        run: |
          echo "Current working directory: $(pwd)"
          echo "Listing files in the current directory:"
          ls -larth

      - name: Check if S3 bucket exists
        run: |
          BUCKET_NAME=${{ env.BUCKET_NAME }}
          if aws s3 ls "s3://$BUCKET_NAME" 2>&1 | grep -q 'NoSuchBucket'; then
            echo "S3 bucket does not exist. Creating..."
            aws s3 mb s3://$BUCKET_NAME
            echo "Created S3 bucket: $BUCKET_NAME"
          else
            echo "S3 bucket already exists: $BUCKET_NAME"
          fi

      - name: Delete and recreate files
        run: |
          LOG_PATH=${{ env.LOG_PATH }}
          LIST_PATH=${{ env.LIST_PATH }}
          POSTLIST_PATH=${{ env.POSTLIST_PATH }}
          if [ -f "$LOG_PATH" ]; then
            echo "Deleting existing log file: $LOG_PATH"
            rm "$LOG_PATH"
          fi
          echo "Creating new log file: $LOG_PATH"
          touch "$LOG_PATH"
          if [ -f "$LIST_PATH" ]; then
            echo "Deleting existing list file: $LIST_PATH"
            rm "$LIST_PATH"
          fi
          echo "Creating new list file: $LIST_PATH"
          touch "$LIST_PATH"
          if [ -f "$POSTLIST_PATH" ]; then
            echo "Deleting existing postlist file: $POSTLIST_PATH"
            rm "$POSTLIST_PATH"
          fi
          echo "Creating new postlist file: $POSTLIST_PATH"
          touch "$POSTLIST_PATH"

      - name: Apt install rclone
        run: |
          sudo apt-get update
          sudo apt-get install -y rclone

      - name: Configure rclone for S3
        run: |
          AWS_REGION=${{ env.AWS_REGION }}
          rclone config create uploads-s3 s3 provider AWS env_auth true region $AWS_REGION
          # rclone config show uploads-s3
  
      - name: Upload to S3 bucket
        run: |
          BUCKET_NAME=${{ env.BUCKET_NAME }}
          TEST_PATH=${{ env.TEST_PATH }}
          LOG_PATH=${{ env.LOG_PATH }}
          if [ -f "$TEST_PATH" ] || [ -d "$TEST_PATH" ]; then
            echo "Uploading $TEST_PATH to S3 bucket: $BUCKET_NAME"
            # aws s3 sync "$TEST_PATH" s3://$BUCKET_NAME/ --delete
            # rclone sync "$TEST_PATH" uploads-s3:"$BUCKET_NAME" --checksum --progress --log-level INFO | tee -a "$LOG_PATH"
            rclone sync "$TEST_PATH" uploads-s3:"$BUCKET_NAME" --checksum --log-level INFO 2>&1 | tee -a "$LOG_PATH"
            echo "Uploaded $TEST_PATH to S3 bucket: $BUCKET_NAME"
          else
            echo "File $TEST_PATH does not exist. Skipping upload."
          fi

      - name: Parse log file and print uploaded files to list file
        run: |
          LOG_PATH=${{ env.LOG_PATH }}
          LIST_PATH=${{ env.LIST_PATH }}
          POSTLIST_PATH=${{ env.POSTLIST_PATH }}
          grep -E "Copied|Deleted" "$LOG_PATH" | awk -F: '{print $2}' | awk '{print $1}' > "$LIST_PATH"
          echo "Uploaded files list saved to: $LIST_PATH"
          while IFS= read -r line; do
            echo "/$line" >> "$POSTLIST_PATH"
          done < "$LIST_PATH"
          cat "$POSTLIST_PATH"

      # - name: Initiate CloudFront invalidation for uploaded files
      #   run: |
      #     POSTLIST_PATH=${{ env.POSTLIST_PATH }}
      #     DISTRIBUTION_ID=${{ vars.CLOUDFRONT_DISTRIBUTION_ID }}
      #     if [ -f "$POSTLIST_PATH" ]; then
      #       echo "Initiating CloudFront invalidation for distribution ID: $DISTRIBUTION_ID"
      #       # aws cloudfront create-invalidation --distribution-id "$DISTRIBUTION_ID" --paths "/*"
      #       aws cloudfront create-invalidation --distribution-id "$DISTRIBUTION_ID" --paths file://"$POSTLIST_PATH"
      #       echo "CloudFront invalidation initiated."
      #     else
      #       echo "Postlist file $POSTLIST_PATH does not exist. Skipping CloudFront invalidation."
      #     fi
 