name: Basic CI Pipeline

on: [pull_request]

# on:
#   push:
#     branches: [ main ]

env:
  AWS_REGION: us-east-1

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:

      # - name: Check out repository code
      #   uses: actions/checkout@v4

      # - name: Log message
      #   run: echo "Hello World! The workflow is running successfully."

      # - name: Run a basic command
      #   run: node --version

      # - name: Install AWS CLI
      #   run: |
      #     curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      #     unzip awscliv2.zip
      #     sudo ./aws/install
      #     aws --version
      
      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v2
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
      - name: Check AWS CLI version
        run: aws --version
      
      - name: Print AWS STS identity
        env:
          AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: aws sts get-caller-identity
